[variable]
registry=dockerregistry:5000
privet_pip=https://pypi.ze.tum.de
product_tag=wos

[betriebsystem]
ubuntu_1=sed -i s/archive.ubuntu.com/ubuntu.mirror.lrz.de/ /etc/apt/sources.list
ubuntu_2=apt-get -y update
ubuntu_3=apt-get -y upgrade
ubuntu_4=apt-get -y dist-upgrade
ubuntu_5=apt-get -y autoremove
ubuntu_6=apt-get -y clean